ngpu: 1
MODEL:
  LABEL: [
  "aeroplane",
  "bicycle",
  "bird",
  "boat",
  "bottle",
  "bus",
  "car",
  "cat",
  "chair",
  "cow",
  "diningtable",
  "dog",
  "horse",
  "motorbike",
  "person",
  "pottedplant",
  "sheep",
  "sofa",
  "train",
  "tvmonitor"
  ]
  numcls: 20
  modeltype: StrongerV3
  backbone: 'mobilenetv2'
  backbone_pretrained: 'checkpoints/mobilenet_v2.pth'
  gt_per_grid: 1

EXPER:
  experiment_name: 'strongerv3'
  train_sizes: [480,512,544]
  test_size: 544
DATASET:
  dataset: 'Custom'
  dataset_root: '/home/gwl/datasets/VOC_dummy'

OPTIM:
  batch_size: 12
  lr_initial: 2e-4
  total_epoch: 60
  milestones: [30,45]

Prune:
  sparse: False