MODEL:
  LABEL: [
  "aeroplane",
  "bicycle",
  "bird",
  "boat",
  "bottle",
  "bus",
  "car",
  "cat",
  "chair",
  "cow",
  "diningtable",
  "dog",
  "horse",
  "motorbike",
  "person",
  "pottedplant",
  "sheep",
  "sofa",
  "train",
  "tvmonitor"
  ]
  numcls: 20
  modeltype: StrongerV3
  backbone: 'mobilenetv2'
  backbone_pretrained: 'checkpoints/mobilenet_v2.pth'
  gt_per_grid: 1

EXPER:
  experiment_name: 'strongerv3_dist'
DATASET:
  dataset: 'VOC'

OPTIM:
  batch_size: 12
  lr_initial: 3e-4
  total_epoch: 50
  milestones: [30,40]

Prune:
  sparse: False

ngpu: 2